### ISSUE TITLE
Modelo de testes

### ISSUE THREAD

**Issue by kyriosdata** [paulohg6/automacao-fhir-Pacient#2]
Notei que os "testes" estão específicos, são bem-definidos. Não teríamos que progredir na direção de um modelo? Adicionalmente, não notei a presença de verificações. Pensei que você tivesse criado testes (scripts) para a verificação. Novamente, não deveriam ser específicos, mas gerais, um modelo, suficiente para ver como poderia ser instanciado.

**Comment by paulohg6** [comment]
Os testes foram ajustados para validar os retornos 201, 200 e validar o header do retorno.
Quanto aos scripts de testes eles se encontram no inicio de cada item no JSON
Segue exemplo abaixo:

"item": [
		{
			"name": "GetPaciente",
			"item": [
				{
					"name": "RecuperandoPacientePeloIDValido2719516Reposta200",
					"event": [
						{
							"listen": "test",
							"script": {
								"id": "682474d7-cc67-40fd-a88d-98dc17e077f6",
								"exec": [
									"pm.test(\"Status code is 200\", function () {",
									"    pm.response.to.have.status(200);",
									"});",
									"",
									"",
									""
								],
								"type": "text/javascript"
							}
						}
					],
